"""
Custom Exception class
"""

class CustomError(Exception):
    pass